apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dx844v9vp-nodejs 
  janus-idp.io/tekton: dx844v9vp-nodejs
  backstage.io/kubernetes-id: dx844v9vp-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dx844v9vp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml