apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dx844v9vp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dx844v9vp-nodejs 
  name: dx844v9vp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dx844v9vp-nodejs 
